//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BAITHI
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public int MABAITHI { get; set; }

        [StringLength(50)]
        public string GIONOPBAI { get; set; }

        [Display(Name = "Diem")]
        public Nullable<int> DIEM { get; set; }

        [Display(Name = "Ma sinh vien")]
        public string MASV { get; set; }

        [Display(Name = "Ma ca thi")]
        public Nullable<int> MACATHI { get; set; }

        [Display(Name = "Tinh trang")]
        public string TINHTRANG { get; set; }
    }
}
