//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAITHI
    {
        public int MABAITHI { get; set; }
        public string GIONOPBAI { get; set; }
        public Nullable<int> DIEM { get; set; }
        public string MASV { get; set; }
        public Nullable<int> MACATHI { get; set; }
    
        public virtual CATHI CATHI { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
        public virtual CT_BAITHI CT_BAITHI { get; set; }
    }
}
