//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATHI()
        {
            this.CT_CATHI = new HashSet<CT_CATHI>();
        }
    
        public int MACATHI { get; set; }
        public string MAHOCPHAN { get; set; }
        public Nullable<int> MADETHI { get; set; }
        public string MADECON { get; set; }
        public Nullable<System.DateTime> NGAYTHI { get; set; }
        public string PHONGTHI { get; set; }
        public string GIOLAMBAI { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
        public Nullable<bool> TINHTRANGTHI { get; set; }
    
        public virtual DETHI DETHI { get; set; }
        public virtual HOCPHAN HOCPHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CATHI> CT_CATHI { get; set; }
    }
}
