//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUHOI()
        {
            this.CT_BAITHI = new HashSet<CT_BAITHI>();
            this.CT_DETHI = new HashSet<CT_DETHI>();
            this.NGANHANGCAUHOI_DADUYET = new HashSet<NGANHANGCAUHOI_DADUYET>();
        }
    
        public int MACAUHOI { get; set; }
        public string NOIDUNG { get; set; }
        public string DAPAN1 { get; set; }
        public string DAPAN2 { get; set; }
        public string DAPAN3 { get; set; }
        public string DAPAN4 { get; set; }
        public string DAPANDUNG { get; set; }
        public Nullable<int> MANGANHANG { get; set; }
        public string MAHOCPHAN { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
    
        public virtual HOCPHAN HOCPHAN { get; set; }
        public virtual NGANHANGCAUHOI NGANHANGCAUHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAITHI> CT_BAITHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DETHI> CT_DETHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGANHANGCAUHOI_DADUYET> NGANHANGCAUHOI_DADUYET { get; set; }
    }
}
