//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DETHI
    {
        public int STT { get; set; }
        public Nullable<int> MADETHI { get; set; }
        public string MADECON { get; set; }
        public Nullable<int> MACAUHOI { get; set; }
    
        public virtual CAUHOI CAUHOI { get; set; }
        public virtual DETHI DETHI { get; set; }
    }
}
