//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_NGANHANGCAUHOI
    {
        public int MANGANHANG { get; set; }
        public string MAGV { get; set; }
        public string MAHOCPHAN { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual HOCPHAN HOCPHAN { get; set; }
        public virtual NGANHANGCAUHOI NGANHANGCAUHOI { get; set; }
    }
}
