//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETHI()
        {
            this.CATHIs = new HashSet<CATHI>();
            this.CT_DETHI = new HashSet<CT_DETHI>();
        }
    
        public int MADETHI { get; set; }
        public string MAHOCPHAN { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> TGLAMBAI { get; set; }
        public Nullable<int> SLCAUHOI { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATHI> CATHIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DETHI> CT_DETHI { get; set; }
        public virtual HOCPHAN HOCPHAN { get; set; }
    }
}
