//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_HETHONGTHITRACNGHIEMEntities6 : DbContext
    {
        public QL_HETHONGTHITRACNGHIEMEntities6()
            : base("name=QL_HETHONGTHITRACNGHIEMEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAITHI> BAITHIs { get; set; }
        public virtual DbSet<CATHI> CATHIs { get; set; }
        public virtual DbSet<CAUHOI> CAUHOIs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CT_BAITHI> CT_BAITHI { get; set; }
        public virtual DbSet<CT_CATHI> CT_CATHI { get; set; }
        public virtual DbSet<CT_DETHI> CT_DETHI { get; set; }
        public virtual DbSet<CT_HOCPHAN> CT_HOCPHAN { get; set; }
        public virtual DbSet<CT_NGANHANGCAUHOI> CT_NGANHANGCAUHOI { get; set; }
        public virtual DbSet<DETHI> DETHIs { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIENs { get; set; }
        public virtual DbSet<HOCPHAN> HOCPHANs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<LOPHOC> LOPHOCs { get; set; }
        public virtual DbSet<NGANHANGCAUHOI> NGANHANGCAUHOIs { get; set; }
        public virtual DbSet<NGANHANGCAUHOI_DADUYET> NGANHANGCAUHOI_DADUYET { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
