//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGANHANGCAUHOI_DADUYET
    {
        public string MANH { get; set; }
        public string MAHOCPHAN { get; set; }
        public int MACAUHOI { get; set; }
    
        public virtual CAUHOI CAUHOI { get; set; }
        public virtual HOCPHAN HOCPHAN { get; set; }
    }
}
