//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThiTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.BAITHIs = new HashSet<BAITHI>();
            this.CT_CATHI = new HashSet<CT_CATHI>();
            this.CT_HOCPHAN = new HashSet<CT_HOCPHAN>();
        }
    
        public string MASV { get; set; }
        public string MAKHAU { get; set; }
        public string TENSV { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public string QUEQUAN { get; set; }
        public string MALOP { get; set; }
        public string HOCPHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAITHI> BAITHIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CATHI> CT_CATHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOCPHAN> CT_HOCPHAN { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
    }
}
